### PR TITLE
Load more

### PR DESCRIPTION
**Pull request by noofherder**
Added "load more" button for terms and doc values.

### CODE REVIEW

**Comment by romseygeek** [comment]
Looks good.  I found one bug - the 'load more' button breaks if you're filtering the docvalues by regex

**Comment by romseygeek** [comment]
Ah, this is because we can't seek on a filtered TermsEnum.  Will see if there's a better way of doing it.

**Comment by romseygeek** [comment]
I think we have to remove the 'load more' button when filtering the values, unfortunately.  Or maybe add an 'offset' parameter, and just call .next() that many times before returning the results?

**Comment by noofherder** [comment]
I think this is working now. In the process I found LUCENE-7646.

**Pull request merged**
